const SET_ERROR = 'SET_ERROR';
const SET_USER = 'SET_USER';
const FETCH_TWEETS = 'FETCH_TWEETS';
const FETCH_TWEETS_SUCCESS = 'FETCH_TWEETS_SUCCESS';
const FETCH_COVID_DATA = 'FETCH_COVID_DATA';
const FETCH_COVID_DATA_SUCCESS = 'FETCH_COVID_DATA_SUCCESS';
const SET_LOADING_AND_ERROR = 'SET_LOADING_AND_ERROR';
const SET_TWEETS_LOADING_AND_ERROR = 'SET_TWEETS_LOADING_AND_ERROR';
const SET_COVID_DATA_LOADING_AND_ERROR = 'SET_COVID_DATA_LOADING_AND_ERROR';

const ACTIONS = {
  SET_ERROR,
  SET_USER,
  FETCH_TWEETS_SUCCESS,
  SET_LOADING_AND_ERROR,
  FETCH_TWEETS,
  SET_TWEETS_LOADING_AND_ERROR,
  FETCH_COVID_DATA,
  FETCH_COVID_DATA_SUCCESS,
  SET_COVID_DATA_LOADING_AND_ERROR,
};

export default ACTIONS;
